
#define SYSTEM_NAME "linux-gnu"
#define HAVE_STDLIB_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_BCOPY 1
#define HAVE_MEMMOVE 1
#define HAVE_STRERROR 1
#define HAVE_TCGETATTR 1
#define HAVE_WAITPID 1
#define HAVE_TERMCAP_H 1
#define USE_TERMINFO 1
#define HAVE_LASTLOG_H 1
#define HAVE_PATHS_H 1
#define USE_LASTLOG 1
#define HAVE_UTMP 1
#define HAVE_UTMP_UT_HOST 1
#define HAVE_UTMP_UT_XSTATUS 1
#define ut_xstatus ut_exit.e_exit
#define HAVE_UTMP_UT_XTIME 1
#define HAVE_UTMP_UT_SESSION 1
#define USE_SYSV_UTMP 1
#define HAVE_POSIX_VDISABLE 1
#define HAVE_ERRNO 1
#define USE_TTY_GROUP 1
#define CC_HAS_PROTOS 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_LIBNSL 1
#define HAVE_LIBXT 1
#define HAVE_X11_DECKEYSYM_H 1
#define HAVE_X11_XPOLL_H 1
