#!/bin/sh -e

if [ "$1" = configure ]; then
    if test -x /usr/bin/update-menus; then update-menus; fi

    update-alternatives --install /usr/bin/x-terminal-emulator \
	x-terminal-emulator /usr/bin/mxterm 10 \
	--slave /usr/share/man/man1/x-terminal-emulator.1.gz \
	x-terminal-emulator.1.gz /usr/share/man/man1/mxterm.1.gz
    pkg=mxterm
fi
